language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - tree

script:
  - cargo build
  - if [ "$TRAVIS_RUST_VERSION" = nightly ]; then
      ci/run.sh;
    fi

branches:
  only: master

notifications:
  email: false
