language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - tree

script:
  - cargo build
  - if [ "$TRAVIS_RUST_VERSION" = nightly ]; then
      cargo install --path .;
      cargo sysroot --target arm-unknown-linux-gnueabihf target/sysroot;
      tree target/sysroot;
    fi

branches:
  only: master

notifications:
  email: false
