[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>"]
license = "MIT/Apache-2.0"
name = "cargo-sysroot"
version = "0.1.0"

[dependencies]
clap = "2.0.2"
fern = "0.3.5"
log = "0.3.5"
rustc_version = "0.1.6"
tempdir = "0.3.4"
tar = "0.4"
flate2 = "0.2"
curl = "0.2"
